### PR TITLE
Update to wgpu 23.0.0

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
The demo is crashing on macOS with a validation error that the surface hasn't been configured. I'm still looking into that.

**Comment by Wumpf** [comment]
looks like the demo only ever does configure on resize. how did this ever work..?

**Comment by waywardmonkeys** [comment]
Well, I think `winit` often sends a resize at startup, but before I ran out of time, I didn't see it happening yesterday.

**Comment by DJMcNab** [comment]
If the demo was already not implemented correctly, is it worth merging this as-is (it seems to have been validated by the author of #89), and moving the issue with the demo to its own issue?

**Comment by waywardmonkeys** [comment]
@Wumpf Looks like just a single line fix to the demo was enough. Hopefully this is good to go now.

**Pull request merged**
