### PR TITLE
Update to wgpu 22.1.0

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This changes a lifetime for scoped render pipelines to match a similar change for `begin_render_pass` in wgpu itself.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Hmm, that's an interesting build failure.

**Comment by waywardmonkeys** [comment]
This failure is due to https://github.com/gfx-rs/wgpu/pull/5988

**Comment by Wumpf** [comment]
Thanks for opening this! Looks like we'll have to wait for `22.1` though or remove the tracy feature for a release 🤔

Since there's already so many people knocking to move forward, I'd say we create an issue about this here to track it and remove tracy and then readd it once there's a wgpu patch release out at which point yet-another wgpu-profiler version releases

**Comment by John-Nagle** [comment]
Don't remove Tracy support! The whole point of this crate is profiling. I need this upgrade so I can look for known performance bugs using a later WGPU. If I report performance bugs for any WGPU other than the very latest, the maintainers want the problem reproduced on the "current version".

**Comment by cwfitzgerald** [comment]
I think we should do a patch release pretty soon, there's a few things that need to be patched

**Comment by Wumpf** [comment]
>  the maintainers want the problem reproduced on the "current version"

ahh these annoying wgpu maintainers 😅 
Yeah, let's get a wgpu patch out there in a timely fashion then instead 👍(:

**Comment by waywardmonkeys** [comment]
Sounds good to me, happy to wait a bit.

**Comment by waywardmonkeys** [comment]
Updated for 22.1.0!

I didn't update all of the stuff ... so maybe that should happen after this and before the release. Just an update to `Cargo.lock`, I think.

**Comment by John-Nagle** [comment]
`version = "0.17.0"`

Needs a version bump so it can be pushed to crates.io.

**Comment by waywardmonkeys** [comment]
Assuming this is about the crate version and not `tracy-client` version ... that would happen as part of a PR for the new version / publish.

I should add a CHANGELOG entry though to this commit to make that easier.

**Comment by Wumpf** [comment]
done so directly on main now and published a new version to crates.io

**Comment by waywardmonkeys** [comment]
Thank you!

**Comment by DJMcNab** [comment]
Should that release have a corresponding [tag](https://github.com/Wumpf/wgpu-profiler/tags) as well?

**Comment by Wumpf** [comment]
ah yes, forgot about that, thx!

**Pull request merged**
