### PR TITLE
wgpu 0.16

### PR DESCRIPTION
**Pull request by Davidster**

### CODE REVIEW

**Review by Wumpf — APPROVED** [review]
thanks! I'll release a new version right away

**Comment by Wumpf** [comment]
@Davidster did this work for you? I made the mistake of not spinning this on a machine that actually runs this code (I'm on a Mac most of the time these days). See https://github.com/gfx-rs/wgpu/issues/3725

**Comment by Davidster** [comment]
happy to help debug this if I can find a way to reproduce the crash locally

**Comment by Wumpf** [comment]
Huh, strange, I wonder what's going on then! Didn't repro myself yet but the bugreport seemed very reasonable 🤔 
Are you perchance using `wgt::Features::MAPPABLE_PRIMARY_BUFFERS`?
And thank you for the lightning fast response!

**Comment by Davidster** [comment]
no problem!

I just tried double checking that I'm using all the features, and it still seems to work:

```rust
let adapter = instance
    .request_adapter(&wgpu::RequestAdapterOptions {
        power_preference: wgpu::PowerPreference::HighPerformance,
        compatible_surface: Some(&surface),
        force_fallback_adapter: false,
    })
    .await
    .expect("Failed to find an appropriate adapter");

let adapter_info = adapter.get_info();
log::info!("Using {} ({:?})", adapter_info.name, adapter_info.backend);

let mut features = adapter.features();

features = features | wgpu_profiler::GpuProfiler::ALL_WGPU_TIMER_FEATURES;
features = features | wgpu::Features::MAPPABLE_PRIMARY_BUFFERS;

let (device, queue) = adapter
    .request_device(
        &wgpu::DeviceDescriptor {
            label: None,
            features,
            limits: wgpu::Limits {
                // the camera is the biggest thing we send in the shader
                max_push_constant_size: (std::mem::size_of::<MeshShaderCameraRaw>()
                    .max(std::mem::size_of::<SkyboxShaderCameraRaw>()))
                    as u32,
                ..Default::default()
            },
        },
        None,
    )
    .await
    .expect("Failed to create device");
```

**Comment by Davidster** [comment]
update: I was able to reproduce the crash on the issue reporter's project

**Comment by Wumpf** [comment]
`let mut features = adapter.features();` if I'm not mistaken that draws in all the features the adapter supports, i.e. also `wgt::Features::MAPPABLE_PRIMARY_BUFFERS` which then causes the validation warning we're seeing on the issue never to trigger 💡

**Comment by Davidster** [comment]
yes, you're right. voidin removed the MAPPABLE_PRIMARY_BUFFERS feature: https://github.com/pudnax/voidin/blob/9de0b63d5306ef788e926a6e0c39d42609de71cd/src/app.rs#L125

**Comment by Wumpf** [comment]
Repros fine with `cargo run --example demo` on Windows.

Somewhat oftopic and ymmv (!), but personally I consider it bad practice to opt-in all features an adapter provides. This makes for much less portable applications - the problem is that one may start using rare features without even noticing so. I think it's pretty powerful that wgpu validates against an explicitly chosen set and doesn't assume that only because something is available on the _current_ machine it should be allowed.

I'll most likely get to a fix later this week, unless ofc one of you wants to take this on (:
Let's continue the conversation on https://github.com/Wumpf/wgpu-profiler/issues/27 (yeah I know, it was me who started necromancing this closed PR!)

**Comment by Davidster** [comment]
gunna give it a shot

**Pull request merged**
